version: '3'
services:
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /home/pi/synced/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=gb
    ports:
      - 8181:8181
