version: "2"

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/wd:/data/
      - /home/pi/synced/openvpn-transmission/:/config
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=youruser
      - OPENVPN_PASSWORD=yourpass
      - OPENVPN_CONFIG=de_frankfurt
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_UTP_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=4
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_GLOBAL=500
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=500
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_IDLE_SEEDING_LIMIT=480
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/data/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/data/torrents/blackhole
      - LOCAL_NETWORK=192.168.0.0/24
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London


  proxy:
    image: haugene/transmission-openvpn-proxy:latest-armhf
    links:
      - transmission
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
