version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - /home/pi/synced/lychee/mariadb/config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /home/pi/synced/lychee/config:/config
      - /media/wd/linuxserver-nextcloud/data/yFvtlonH9kaoutHsv/files/Photos/testfolder:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - 8090:80