version: '3'
services:
  rclone_rclone:
    image: rclone/rclone
    container_name: rclone
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user user --rc-pass pass --transfers 1 --cutoff-mode soft --rc-web-gui-no-open-browser --rc-web-gui-update
    ports:
      - "5572:5572"
    volumes:
      - /home/pi/synced/rclone/config:/config/rclone
      - /media/wd:/data/wd:shared
      - /media/hdd/videos:/data/hdd/videos:shared
      - /home/pi/synced:/data/synced
      - /home/pi/synced_backup:/data/synced_backup
    environment:
      - PHP_TZ=Europe/London
      - PUID=1000
      - PGID=1000
