version: "3.7"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    environment:
      - VPNSP=private internet access
      - REGION=UK London
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
    volumes:
      - /home/pi/synced/gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9117:9117
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped